services:
  redis:
    image: redis:7
    container_name: redis_app
    command:
      --port 5370
    expose:
      - 5370
  bot:
    build:
      context: .
    env_file:
      - .env
    container_name: course_tracker
    command: ["/coursetracker/bot.sh"]
    depends_on:
      - redis
